### ISSUE TITLE
Container is crashing

### ISSUE THREAD

**Issue by sr-as2** [thiagobruch/HA_Addons#10]
Hi!
Alexa sync was working a couple of days, but now i've got a crashed, the container is crashing with error:

```
/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:59
            this.#timeoutError = new Errors_js_1.TimeoutError(opts.message);
                                 ^

TimeoutError: Navigation timeout of 60000 ms exceeded
    at new Deferred (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:59:34)
    at Deferred.create (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:21:16)
    at new LifecycleWatcher (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/LifecycleWatcher.js:69:60)
    at CdpFrame.waitForNavigation (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:199:29)
    at CdpFrame.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
    at CdpPage.waitForNavigation (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:619:43)
    at /app/scrapeAmazon.js:117:24
```

Any idea?

**Comment by thiagobruch** [comment]
Hi @sr-as2

Would that by any chance the german version (i.e. https://amazon.de) ?

If so, can you try pulling the new version of the Addon (1.0.32)?

**Comment by sr-as2** [comment]
I'm using the french version :)
Since some HA updates, i have a notification in HA who says:

> Add-on Alexa Shopping List Scrapper has been removed from the repository it was installed from. This means it will not get updates, and backups may not be restored correctly as the supervisor may not be able to build/download the resources required.


I'm using https://github.com/thiagobruch/HA_Addons HA repository

**Comment by thiagobruch** [comment]
@sr-as2 

Sorry about that.
I'm still learning github and the addon format with Home Assistant.

Can you try to download the Addon again? You check for updates and refresh and it should be good to install.

**Comment by sr-as2** [comment]
Great thanks, i update to 1.0.32 but same error:

```
/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:59
            this.#timeoutError = new Errors_js_1.TimeoutError(opts.message);
                                 ^

TimeoutError: Navigation timeout of 60000 ms exceeded
    at new Deferred (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:59:34)
    at Deferred.create (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:21:16)
    at new LifecycleWatcher (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/LifecycleWatcher.js:69:60)
    at CdpFrame.waitForNavigation (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:199:29)
    at CdpFrame.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
    at CdpPage.waitForNavigation (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:619:43)
    at /app/scrapeAmazon.js:126:24
```


My Amazon signin url:
`https://www.amazon.fr/ap/signin?openid.pape.max_auth_age=900&openid.return_to=https%3A%2F%2Fwww.amazon.fr%2Fgp%2Fyourstore%2Fhome%3Fpath%3D%252Fgp%252Fyourstore%252Fhome%26signIn%3D1%26useRedirectOnSuccess%3D1%26action%3Dsign-out%26ref_%3Dnav_AccountFlyout_signout&openid.assoc_handle=frflex&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0`

**Comment by thiagobruch** [comment]
When I open on mine for the first time, I get this screen
<img width="587" alt="image" src="https://github.com/user-attachments/assets/81ff5937-de6c-4570-a00a-9e5328d4b54e">
Once I open the second time, it goes away and straight into the Sign In page

I removed the timeout from the first page (in your case the app will try to access https://www.amazon.fr/).
Can you uninstall, refresh (check for updates) and install again to try?

**Comment by sr-as2** [comment]
Same error.
for me, when I open on mine for the first time, I get this screen:
![image](https://github.com/user-attachments/assets/b6b1acbe-d4bc-4ac4-85cd-99af292fc81d)

I'll try tomorrow !

**Comment by sr-as2** [comment]
Hi @thiagobruch 
this morning, always a timeout :)
Do you need extra information ?

Regards

**Comment by thiagobruch** [comment]
Hi @sr-as2.

I created a new version of the Addon using Alpine and added some debug info.
Please uninstall, then reinstall the BETA version.
In the Configuration Tab, click on "Show unused optional configuration options" and select "Debug" under log_level.
Add your info, save and run the container.

Once it fails, try going to http://homeassistant.local:8888 and check the screenshots saved.

**Comment by sr-as2** [comment]
Hi thanks for your help!
The result:
(seems the password is not set ? i have complex caracter in it)

![2024-08-24T09-42-25-933Z-01-screenshot_main_page](https://github.com/user-attachments/assets/a15ac842-2648-4f6a-8217-67f5b1875ff2)
![2024-08-24T09-42-28-222Z-02-screenshot_login_page](https://github.com/user-attachments/assets/03e23bd2-6e27-439a-bfcb-0e7ffde00e3e)
![2024-08-24T09-42-29-468Z-03 2-screenshot_login_only_and_pass_page](https://github.com/user-attachments/assets/ae59755c-400d-4f46-b869-4cfd4fd98396)
![2024-08-24T09-42-30-422Z-03 3-screenshot_pass_only_and_pass_page](https://github.com/user-attachments/assets/036decf8-61e0-47e8-b329-a0215d53a16e)

**Comment by thiagobruch** [comment]
@sr-as2,

I added couple more screenshots. Can you try uninstall, reinstall, go to config to enable the debug and run again.

Please send me the screenshots (make sure any sensitive information is covered)

**Comment by sr-as2** [comment]
here are the additional screenshots. The others are the same:

![2024-08-25T09-43-45-498Z-03 3-screenshot_pass_only_before_page](https://github.com/user-attachments/assets/93dbbb13-3e47-4c11-ac06-00711f89c106)
![2024-08-25T09-43-45-685Z-03 4-screenshot_pass_only_after_page](https://github.com/user-attachments/assets/3a75e9ef-f8d1-43aa-9d35-b3ea7e9dde69)

**Comment by thiagobruch** [comment]
It is weird that it doesn't look like it is "typing" the password.
I'm adding another debug line that will list all the IDs found in the page.
It will show in the log once it runs.

**Comment by sr-as2** [comment]
Hi @thiagobruch 
It's working now! With the last beta.
FYI:
```
[
  'a-page',
  'authportal-center-section',
  'authportal-main-section',
  'auth-cookie-warning-message',
  'passkey-error-alert',
  'passkey-client-error-message',
  'passkey-generic-server-error-message',
  'passkey-server-error-message',
  'auth-email-claim',
  'ap_change_login_claim',
  'ap_email',
  'ap-credential-autofill-hint',
  'auth-fpp-link-bottom',
  'passwordErrorAnnounce',
  'ap_password',
  'auth-password-missing-alert',
  'auth-signin-button',
  'signInSubmit',
  'auth-signin-button-announce',
  'kmsi-weblab-treatment',
  'remember_me_learn_more_link',
  'ap-signin-alternative-option-divider',
  'auth-signin-via-passkey-section',
  'auth-signin-via-passkey-btn',
  'continue',
  'right-2',
  'auth-external-javascript',
  'be',
  'a-popover-root'
]
```
