### ISSUE TITLE
OTP Password

### ISSUE THREAD

**Issue by marioir2001** [thiagobruch/HA_Addons#13]
Hello, the add-on works great so far, but I get an SMS with my OTP password every 3 minutes. I copied the 13x4 digit code from Amazon and copied it into the right place. The synchronization still works, even if I ignore the SMS.

**Comment by thiagobruch** [comment]
Hi @marioir2001,

It looks like in your account, the SMS is already setup as the default method.
Try to disabled it and enable again the the 2FA with SMS:

1 - Login to Amazon https://www.amazon.com/
2 - Go to Your Account => Login & Security and click on "Manage" under 2-step verification
3 - Set the Authenticator App as the Prefer method.
4 - Set the SMS as the Backup Method.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/81fd7659-d457-4fd9-8f1c-fe0ff60963e7">

**Comment by marioir2001** [comment]
Thank you for the explanation.
This procedure worked great. Now I no longer receive annoying OTP requests via SMS
