### ISSUE TITLE
Error: No element found for selector: #ap_password

### ISSUE THREAD

**Issue by metalmarco** [thiagobruch/HA_Addons#9]
I've followed the whole procedure but I'm getting this error.

```
s6-rc: info: service legacy-services successfully started
/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18
        throw new Error(message);
              ^

Error: No element found for selector: #ap_password
    at assert (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18:15)
    at CdpFrame.type (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:865:40)
    at async /app/scrapeAmazon.js:115:13

Node.js v21.7.3
s6-rc: info: service legacy-services: stopping
```

I think something is not clear in the instruction provided.
I'm using the italian amazon.it.

Here are my doubts, in order.

**1. In the README in says:**
> This project was crerated using the Amazon USA pages. If you are using amazon in a different location, change the scrapperAmazon.js URLs.

- Is this required even if we have the configuration variables where we set the italian login page?
- If this is required, where exactly is this file located, considering I've installed the AddOns through Home Assistant?
- Also the `scrapperAmazon.js` file is not correct. It's called `scrapeAmazon.js` in your source code.

**2. How to get your OTP App Secret from Amazon**
In the README it says
> 1 - Login to Amazon https://www.amazon.com/
- Is this URL valid even for non-US users? Or should we log in to our country amazon url?

> 5 - Remove the spaces of the Key (you will have something like this "ASDMASDFMSKDMKSFMKLASDDADABB6JNRNF7WFEHQW23H238R7843")

- What should we do on the Amazon page after we copied that code? Should we left it open? Because if we don't do something the authenticator app is not saved

**3. Configuration Tab**
In the README it says
> Amazon_Secret: <YOUR_OTP_APP_SECRET> \ # your OTP App Secret in this format myotpsecrete1234. 

- What exactly is this code? Is it the one we've got from the step 5 of "How to get your OTP App Secret from Amazon"? ("ASDMASDFMSKDMKSFMKLASDDADABB6JNRNF7WFEHQW23H238R7843")
Without knowing exactly what to do, I used that code in this configuration item

**4. Error on Add On Start**
As mentioned above, I'm getting the `Error: No element found for selector: #ap_password` after starting the Addon.
- Is this a puppeteer error, because it's not finding the input in the page?
- Is this because of some wrong configuration in the OTP App or in the Amazon URL?

I'm more than happy to help you debug this error.

Thanks for your work,
Marco

**Comment by metalmarco** [comment]
Ok a little update.
I was able to somehow get this working, but my HA Shopping List is currently not being updated.
I think that if I'm able to get everything working, I can help you write a better README.

I think puppetteer is working correctly, I can see that my Amazon Shopping List is being deleted every 3 minutes.

However, the automation created through the BluePrint is never being called by the AddOn.

This is my Automation WebHook configuration.

What am I doing wrong?

<img width="807" alt="Screenshot 2024-08-21 alle 13 22 24" src="https://github.com/user-attachments/assets/a9bc4b68-2091-4210-843e-acb8835f56a6">


Also, another being problem is receiving an SMS from Amazon every 3 minutes with the OTP code. How can we fix this?

**Comment by metalmarco** [comment]
Found the problem.
If you use Nabu Cloud, you need to activate the WebHook under HA Settings and use that URL in the AddOn configuration.

**Comment by thiagobruch** [comment]
Hi @metalmarco,

Please find some comments below:
> **1. In the README in says:**
> 
> > This project was crerated using the Amazon USA pages. If you are using amazon in a different location, change the scrapperAmazon.js URLs.
> 
> * Is this required even if we have the configuration variables where we set the italian login page?
> * If this is required, where exactly is this file located, considering I've installed the AddOns through Home Assistant?
> * Also the `scrapperAmazon.js` file is not correct. It's called `scrapeAmazon.js` in your source code.
**Comment:** The instructions were copied from the Docker Container Instructions (before the Addon was created).
I changed the README to reflect the new config.


> **2. How to get your OTP App Secret from Amazon** In the README it says
> 
> > 1 - Login to Amazon https://www.amazon.com/
> 
> * Is this URL valid even for non-US users? Or should we log in to our country amazon url?
**Comment:** The URL is just an example. You should use the URL from your country.

> > 5 - Remove the spaces of the Key (you will have something like this "ASDMASDFMSKDMKSFMKLASDDADABB6JNRNF7WFEHQW23H238R7843")
> 
> * What should we do on the Amazon page after we copied that code? Should we left it open? Because if we don't do something the authenticator app is not saved
**Comment:** Adding that to the instructions in the README

> **3. Configuration Tab** In the README it says
> 
> > Amazon_Secret: <YOUR_OTP_APP_SECRET> \ # your OTP App Secret in this format myotpsecrete1234.
> 
> * What exactly is this code? Is it the one we've got from the step 5 of "How to get your OTP App Secret from Amazon"? ("ASDMASDFMSKDMKSFMKLASDDADABB6JNRNF7WFEHQW23H238R7843")
>   Without knowing exactly what to do, I used that code in this configuration item
**Comment:** There is a link in the end of the line that points to instructions "How to get your OTP App Secret from Amazon:".

> **4. Error on Add On Start** As mentioned above, I'm getting the `Error: No element found for selector: #ap_password` after starting the Addon.
> 
> * Is this a puppeteer error, because it's not finding the input in the page?
> * Is this because of some wrong configuration in the OTP App or in the Amazon URL?
**Comment:** The error indicates that puppeteer did not find the item "#ap_password".
This is usually related to a wrong sing-in URL.

**Comment by metalmarco** [comment]
Perfect, thank you @thiagobruch 

There's also a typo in the README for the Italian Shopping list URL www.amazon.com.it shoud be www.amazon.it

I was also able to avoid getting an SMS from Amazon every 3 minutes, by changing my default 2FA provided from SMS to Authenticator App.

**Comment by thiagobruch** [comment]
Hi @metalmarco,

Thank you. I will change the Italian URL.
I didn't try that, but copied form somewhere as an example :)

**Comment by thiagobruch** [comment]
@metalmarco can this be closed?

**Comment by metalmarco** [comment]
Sure! Thanks.

**Comment by giakokiko** [comment]
Hi, @thiagobruch, I'll start by saying that I've been using your addon since version 1.0.32 where I've never encountered any problems. While in the last two days, with the latest version 1.0.35, I've noticed that the addon after some time from its regular functioning, remains started but no longer works, stopping it gives me the same error reported above in the logs. Restarting the addon everything works perfectly but it happens randomly that I find it stopped without doing its job.
I'm using the italian amazon.it

LOG:

```
/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18
        throw new Error(message);
              ^

Error: No element found for selector: #ap_password
    at assert (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18:15)
    at CdpFrame.type (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:865:40)
    at async /app/scrapeAmazon.js:124:13

Node.js v21.7.3
```

Thanks for your work!!
